name: aetheria_graph_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.5
  supabase_flutter: ^2.12.4
  image_picker: ^1.1.2
  flutter_gen: ^5.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true 
  assets:
      - assets/images/