import 'package:flutter/material.dart';
import 'package:aetheria_graph_app/l10n/app_localizations.dart';

List<Map<String, dynamic>> getLocalizedBreathingTechniques(
  BuildContext context,
) {
  final l10n = AppLocalizations.of(context)!;

  return [
    // --- КАТЕГОРІЯ: CHILL (Розслаблення) ---
    {
      "title": l10n.technique478Title,
      "subtitle": l10n.technique478Subtitle,
      "category": "Chill",
      "icon": Icons.self_improvement,
      "color": const Color(0xFF8E44AD),
      "mode": l10n.modeRelaxation,
      "pattern": {"inhale": 4, "hold": 7, "exhale": 8, "holdAfter": 0},
      "durationSeconds": 120,
    },
    {
      "title": l10n.techniqueEqualTitle,
      "subtitle": l10n.techniqueEqualSubtitle,
      "category": "Chill",
      "icon": Icons.waves,
      "color": const Color(0xFF3498DB),
      "mode": l10n.modeBalance,
      "pattern": {"inhale": 4, "hold": 0, "exhale": 4, "holdAfter": 0},
      "durationSeconds": 300,
    },
    {
      "title": l10n.techniqueCoherentTitle,
      "subtitle": l10n.techniqueCoherentSubtitle,
      "category": "Chill",
      "icon": Icons.spa,
      "color": const Color(0xFF1ABC9C),
      "mode": l10n.modeZen,
      "pattern": {"inhale": 6, "hold": 0, "exhale": 6, "holdAfter": 0},
      "durationSeconds": 360,
    },
    {
      "title": l10n.techniqueAntiAnxietyTitle,
      "subtitle": l10n.techniqueAntiAnxietySubtitle,
      "category": "Chill",
      "icon": Icons.favorite,
      "color": const Color(0xFFE74C3C),
      "mode": l10n.modeCalm,
      "pattern": {"inhale": 4, "hold": 4, "exhale": 6, "holdAfter": 2},
      "durationSeconds": 180,
    },

    // --- КАТЕГОРІЯ: FOCUS (Концентрація) ---
    {
      "title": l10n.techniqueBoxTitle,
      "subtitle": l10n.techniqueBoxSubtitle,
      "category": "Focus",
      "icon": Icons.crop_square,
      "color": const Color(0xFFF1C40F),
      "mode": l10n.modeTactical,
      "pattern": {"inhale": 4, "hold": 4, "exhale": 4, "holdAfter": 4},
      "durationSeconds": 240,
    },
    {
      "title": l10n.techniqueTriangleTitle,
      "subtitle": l10n.techniqueTriangleSubtitle,
      "category": "Focus",
      "icon": Icons.change_history,
      "color": const Color(0xFFE67E22),
      "mode": l10n.modeSharpen,
      "pattern": {"inhale": 4, "hold": 4, "exhale": 4, "holdAfter": 0},
      "durationSeconds": 180,
    },
    {
      "title": l10n.techniqueMemoryTitle,
      "subtitle": l10n.techniqueMemorySubtitle,
      "category": "Focus",
      "icon": Icons.psychology,
      "color": const Color(0xFFD35400),
      "mode": l10n.modeMind,
      "pattern": {"inhale": 5, "hold": 2, "exhale": 5, "holdAfter": 0},
      "durationSeconds": 300,
    },
    {
      "title": l10n.techniqueAlphaTitle,
      "subtitle": l10n.techniqueAlphaSubtitle,
      "category": "Focus",
      "icon": Icons.blur_on,
      "color": const Color(0xFF27AE60),
      "mode": l10n.modeFlow,
      "pattern": {"inhale": 4, "hold": 2, "exhale": 4, "holdAfter": 2},
      "durationSeconds": 300,
    },

    // --- КАТЕГОРІЯ: SLEEP (Сон) ---
    {
      "title": l10n.techniqueDeepSleepTitle,
      "subtitle": l10n.techniqueDeepSleepSubtitle,
      "category": "Sleep",
      "icon": Icons.nights_stay,
      "color": const Color(0xFF2C3E50),
      "mode": l10n.modeNight,
      "pattern": {"inhale": 4, "hold": 2, "exhale": 8, "holdAfter": 0},
      "durationSeconds": 420,
    },
    {
      "title": l10n.techniqueLunarTitle,
      "subtitle": l10n.techniqueLunarSubtitle,
      "category": "Sleep",
      "icon": Icons.brightness_3,
      "color": const Color(0xFF5D6D7E),
      "mode": l10n.modeMoon,
      "pattern": {"inhale": 3, "hold": 3, "exhale": 6, "holdAfter": 0},
      "durationSeconds": 300,
    },
    {
      "title": l10n.techniqueDeltaTitle,
      "subtitle": l10n.techniqueDeltaSubtitle,
      "category": "Sleep",
      "icon": Icons.bedtime,
      "color": const Color(0xFF34495E),
      "mode": l10n.modeDelta,
      "pattern": {"inhale": 5, "hold": 5, "exhale": 5, "holdAfter": 5},
      "durationSeconds": 480,
    },
    {
      "title": l10n.techniqueMuscleTitle,
      "subtitle": l10n.techniqueMuscleSubtitle,
      "category": "Sleep",
      "icon": Icons.airline_seat_flat,
      "color": const Color(0xFF1C2833),
      "mode": l10n.modeRelease,
      "pattern": {"inhale": 4, "hold": 1, "exhale": 7, "holdAfter": 0},
      "durationSeconds": 360,
    },

    // --- КАТЕГОРІЯ: ENERGIZE (Енергія) ---
    {
      "title": l10n.techniqueFireTitle,
      "subtitle": l10n.techniqueFireSubtitle,
      "category": "Energize",
      "icon": Icons.whatshot,
      "color": const Color(0xFFE67E22),
      "mode": l10n.modeFire,
      "pattern": {"inhale": 1, "hold": 0, "exhale": 1, "holdAfter": 0},
      "durationSeconds": 60,
    },
    {
      "title": l10n.techniqueBellowsTitle,
      "subtitle": l10n.techniqueBellowsSubtitle,
      "category": "Energize",
      "icon": Icons.flash_on,
      "color": const Color(0xFFFFCC00),
      "mode": l10n.modeBoost,
      "pattern": {"inhale": 2, "hold": 1, "exhale": 2, "holdAfter": 0},
      "durationSeconds": 90,
    },
    {
      "title": l10n.techniqueTummoTitle,
      "subtitle": l10n.techniqueTummoSubtitle,
      "category": "Energize",
      "icon": Icons.storm,
      "color": const Color(0xFFC0392B),
      "mode": l10n.modeHeat,
      "pattern": {"inhale": 2, "hold": 2, "exhale": 1, "holdAfter": 0},
      "durationSeconds": 120,
    },
    {
      "title": l10n.techniqueWakeTitle,
      "subtitle": l10n.techniqueWakeSubtitle,
      "category": "Energize",
      "icon": Icons.light_mode,
      "color": const Color(0xFFF39C12),
      "mode": l10n.modeWake,
      "pattern": {"inhale": 1, "hold": 1, "exhale": 1, "holdAfter": 1},
      "durationSeconds": 90,
    },
  ];
}
