import 'package:flutter/material.dart';

final List<Map<String, dynamic>> breathingTechniques = [
  // CHILL (Relax)
  {
    "title": "4-7-8 Breathing",
    "subtitle": "Instant calm & anxiety relief",
    "mode": "RELAX",
    "category": "Chill",
    "duration": "5 min",
    "icon": Icons.air_outlined,
    "color": const Color(0xFF7000FF),
  },
  {
    "title": "Deep Belly",
    "subtitle": "Abdominal breathing for zen",
    "mode": "ZEN",
    "category": "Chill",
    "duration": "10 min",
    "icon": Icons.spa_rounded,
    "color": const Color(0xFF7000FF),
  },
  {
    "title": "Moon Piercing",
    "subtitle": "Cooling energy and calmness",
    "mode": "BALANCE",
    "category": "Chill",
    "duration": "7 min",
    "icon": Icons.brightness_3_rounded,
    "color": const Color(0xFF7000FF),
  },
  {
    "title": "Zen Flow",
    "subtitle": "Long rhythmic exhalations",
    "mode": "MEDITATION",
    "category": "Chill",
    "duration": "15 min",
    "icon": Icons.self_improvement_rounded,
    "color": const Color(0xFF7000FF),
  },

  // FOCUS
  {
    "title": "Box Breathing",
    "subtitle": "Clear mind & elite focus",
    "mode": "DEEP FOCUS",
    "category": "Focus",
    "duration": "4 min",
    "icon": Icons.crop_square_rounded,
    "color": const Color(0xFFFF007F),
  },
  {
    "title": "Lion's Breath",
    "subtitle": "Release tension & recharge",
    "mode": "CLARITY",
    "category": "Focus",
    "duration": "3 min",
    "icon": Icons.emoji_emotions_outlined,
    "color": const Color(0xFFFF007F),
  },
  {
    "title": "Coherence",
    "subtitle": "Synchronize heart and brain",
    "mode": "HARMONY",
    "category": "Focus",
    "duration": "8 min",
    "icon": Icons.favorite_border_rounded,
    "color": const Color(0xFFFF007F),
  },
  {
    "title": "Mindful Clarity",
    "subtitle": "Sharp attention for work",
    "mode": "BRAIN BOOST",
    "category": "Focus",
    "duration": "6 min",
    "icon": Icons.psychology_outlined,
    "color": const Color(0xFFFF007F),
  },

  // ENERGIZE
  {
    "title": "Breath of Fire",
    "subtitle": "Rapid detox & wake up",
    "mode": "POWER",
    "category": "Energize",
    "duration": "2 min",
    "icon": Icons.local_fire_department_rounded,
    "color": Colors.orange,
  },
  {
    "title": "Skull Shining",
    "subtitle": "Cleanse your energy field",
    "mode": "GLOW",
    "category": "Energize",
    "duration": "5 min",
    "icon": Icons.wb_sunny_outlined,
    "color": Colors.orange,
  },
  {
    "title": "Wim Hof Style",
    "subtitle": "Immunity and inner fire",
    "mode": "ULTIMATE",
    "category": "Energize",
    "duration": "10 min",
    "icon": Icons.ac_unit_rounded,
    "color": Colors.orange,
  },
  {
    "title": "Solar Flare",
    "subtitle": "Pure adrenaline flow",
    "mode": "BOOST",
    "category": "Energize",
    "duration": "3 min",
    "icon": Icons.bolt_rounded,
    "color": Colors.orange,
  },

  // SLEEP
  {
    "title": "Night Fall",
    "subtitle": "Prepare body for rest",
    "mode": "DREAMING",
    "category": "Sleep",
    "duration": "12 min",
    "icon": Icons.nights_stay_rounded,
    "color": Colors.blueAccent,
  },
  {
    "title": "Slowing Heart",
    "subtitle": "Lower BPM before bed",
    "mode": "SLOW DOWN",
    "category": "Sleep",
    "duration": "15 min",
    "icon": Icons.monitor_heart_outlined,
    "color": Colors.blueAccent,
  },
  {
    "title": "Delta Wave",
    "subtitle": "Enter deep sleep cycles",
    "mode": "RECOVERY",
    "category": "Sleep",
    "duration": "20 min",
    "icon": Icons.bedtime_outlined,
    "color": Colors.blueAccent,
  },
  {
    "title": "Dream Weaver",
    "subtitle": "Lucid dreaming prep",
    "mode": "RELAX",
    "category": "Sleep",
    "duration": "10 min",
    "icon": Icons.auto_awesome_rounded,
    "color": Colors.blueAccent,
  },
];

final List<String> categories = ["All", "Chill", "Focus", "Sleep", "Energize"];
